#!/usr/bin/env bash
# scripts/worktree-setup.sh — provision per-worktree env so each worktree's desktop
# (and future web/sync-api) point at their own derived ports, with zero clashes.
#
# Usage: scripts/worktree-setup.sh <worktree_path>

set -euo pipefail

WT_DIR="${1:?usage: worktree-setup.sh <worktree_path>}"
WT_DIR="$(cd "$WT_DIR" && pwd)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib/ports.sh
source "$SCRIPT_DIR/lib/ports.sh"

# Resolve the MAIN worktree (first entry of `git worktree list --porcelain`).
MAIN_ROOT="$(git -C "$WT_DIR" worktree list --porcelain 2>/dev/null \
              | awk '/^worktree /{print $2; exit}')"
MAIN_ROOT="${MAIN_ROOT:-$WT_DIR}"

# Reset any inherited overrides so this worktree's ports come from ITS path.
unset VITE_PORT WEB_PORT SYNC_API_PORT
derive_ports "$WT_DIR"

# --- desktop/.env.local: point Tauri/Vite client at THIS worktree's sync-api ---
# (sync-api doesn't exist yet — this is forward-compatible wiring.)
mkdir -p "$WT_DIR/apps/desktop"
cat > "$WT_DIR/apps/desktop/.env.local" <<EOF
# Auto-generated by scripts/worktree-setup.sh — do not commit.
# Worktree: $WT_NAME
VITE_SYNC_API_URL=http://localhost:$SYNC_API_PORT
EOF

# --- sync-api/.env: carry secrets if a main checkout has them (future) ---------
if [ -f "$MAIN_ROOT/apps/sync-api/.env" ]; then
  mkdir -p "$WT_DIR/apps/sync-api"
  cp "$MAIN_ROOT/apps/sync-api/.env" "$WT_DIR/apps/sync-api/.env"
  echo "[worktree-setup] copied apps/sync-api/.env from main checkout"
fi

# --- .vscode/: auto-launch claude in the integrated terminal on folder open ----
mkdir -p "$WT_DIR/.vscode"
cat > "$WT_DIR/.vscode/settings.json" <<'EOF'
{
  "task.allowAutomaticTasks": "on"
}
EOF
cat > "$WT_DIR/.vscode/tasks.json" <<'EOF'
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "claude",
      "type": "shell",
      "command": "claude",
      "presentation": {
        "reveal": "always",
        "panel": "new",
        "focus": true,
        "clear": true,
        "showReuseMessage": false
      },
      "runOptions": { "runOn": "folderOpen" },
      "problemMatcher": []
    }
  ]
}
EOF

echo "[worktree-setup] $WT_NAME: vite=$VITE_PORT web=$WEB_PORT sync_api=$SYNC_API_PORT"
echo "[worktree-setup] wrote apps/desktop/.env.local + .vscode/{tasks,settings}.json"
